doskey v=nvim $*
doskey vi=vim $*
doskey n=cd $*
doskey g=git $*
doskey e=%EDITOR% $*
doskey l=lfcd.cmd
doskey ls=dir /B $*
doskey cp=copy $*
doskey mv=move $*
doskey pwd=cd
doskey rm=del $*
doskey clear=cls
doskey lynx=lynx -cfg %USERPROFILE%\.config\lynx\lynx.cfg $*
doskey cat=type $*
