set HOME=%USERPROFILE%
set XDG_CONFIG_HOME=%USERPROFILE%\.config
set XDG_DATA_HOME=%USERPROFILE%\.local\share
set XDG_CACHE_HOME=%USERPROFILE%\.cache
set VISUAL=vim
set EDITOR=%VISUAL%

set GNUPGHOME=%XDG_DATA_HOME%\gnupg
set GPGHOME=%XDG_DATA_HOME%\gnupg
set PASSWORD_STORE_DIR=%XDG_DATA_HOME%\pass
set PASS_BASE_DIR=%XDG_DATA_HOME%\pass
set NB_PATH=%XDG_DATA_HOME%\notebook

set MYVIMRC=%XDG_CONFIG_HOME%\vim\vimrc
set VIMINIT=source $MYVIMRC
set PATH=%PATH%;%USERPROFILE%\.local\bin\cmd
