if !has('nvim')
	if has("&viminfofile")
		set viminfofile=$XDG_CACHE_DIR/vim/viminfo
	endif
endif

" General
set nocompatible
set number
set mouse=
set nocursorline
set exrc

" Turn backup off
set nobackup
set nowb
set noswapfile

" Map leader to space
nnoremap <space> <Nop>
let mapleader = " "

" Enable hidden buffers
set hidden

" Disable auto fixing end of line
" Useful when opening binary files
set nofixendofline

" Disable vim intro message
set shortmess=Iat

" Search
set hlsearch
set incsearch
set nowrapscan

" Pro tab
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

" Netrw customization
let g:netrw_banner = 0
let g:netrw_liststyle = 3

" Disable status
set laststatus=1

set lazyredraw
set ttyfast
set nospell

set background=dark
syntax on indent off
source $XDG_CONFIG_HOME/vim/hyper-red.vim

" Plugins
source $XDG_CONFIG_HOME/vim/plugin/plugin.vim

" Keybindings
source $XDG_CONFIG_HOME/vim/keybindings.vim

set packpath^=$XDG_DATA_HOME/vim
set packpath^=$XDG_DATA_HOME/vimcommon

function! s:load_plugins(t) abort
	set synmaxcol=128
	" Use XDG Paths for vim
	" TODO compile hard constants somewhere based on OS
	set runtimepath^='$XDG_CONFIG_HOME/vim'
	set runtimepath+='$XDG_DATA_HOME/vim'
	set runtimepath+='$XDG_CONFIG_HOME/vim/after'

	let g:netrw_home = $XDG_DATA_HOME . "/vim"
	call mkdir($XDG_DATA_HOME . "/vim/spell", 'p')
	set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')

	set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
	set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
	set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')
	packadd vim-tmux-navigator
	packadd vim-commentary
	packadd mru
	packadd vim-surround
	packadd vim-ninja-feet
	packadd vim-fugitive
	packadd vim-better-whitespace
	packadd gruvbox-material
endfunction

augroup user_cmds
	autocmd!
	autocmd VimEnter * call timer_start(20, function('s:load_plugins'))
augroup END

function! SetColorColumnColor()
  if &background ==# 'dark'
    source $XDG_CONFIG_HOME/vim/hyper-red.vim
  endif
endfunction
autocmd OptionSet background call SetColorColumnColor()

if has("gui")
	source $XDG_CONFIG_HOME/vim/gvimrc
endif

if has("win32")
	set shell=cmd
	set shellquote=\" 
	" shellxquote must be a literal space character.
	set shellxquote=  
endif
