set packpath^=$XDG_DATA_HOME/vim

let g:minisnip_dir=$XDG_DATA_HOME . '/vim/minisnip'

set nocursorline
set background=dark

source $XDG_DATA_HOME/vim/hyper-red.vim

set noexpandtab

set path+=**
set wildignore+=**/out/**
